<a href="https://colab.research.google.com/github/LongLongoooo/AIO_233/blob/Exercise_3/Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#Q1
import torch
import torch.nn as nn
import math

In [10]:
class Softmax(nn.Module):
  def __init__(self):
    super(Softmax, self).__init__() #call the constructor of nn.Module

  def forward(self, x):
    exp_x = torch.exp(x)
    sum_exp_x = torch.sum(exp_x)
    return exp_x / sum_exp_x

class softmaxStable(nn.Module):
  def __init__(self):
    super(softmaxStable, self).__init__()

  def forward(self, x):
    c = torch.max(x)
    exp_x = torch.exp(x - c)
    sum_exp_x = torch.sum(exp_x)
    return exp_x/sum_exp_x



In [11]:
data = torch.Tensor([1,2,3])
softmax = Softmax()
output = softmax(data)

output

tensor([0.0900, 0.2447, 0.6652])

In [12]:
data = torch.Tensor([1,2,3])
softmax_stable = softmaxStable()
output = softmax_stable(data)

output

tensor([0.0900, 0.2447, 0.6652])

In [94]:
#Q2
class Student:
  def __init__(self, name, year_of_birth, grade):
    self.name = name
    self.year_of_birth = year_of_birth
    self.grade = grade
  def describe(self):
    print(f"{self.name} - YoB: {self.year_of_birth} - Grade: {self.grade}")

class Teacher:
  def __init__(self, name, year_of_birth, subject):
    self.name = name
    self.year_of_birth = year_of_birth
    self.subject = subject
  def describe(self):
    print(f"{self.name} - YoB: {self.year_of_birth} - Subject: {self.subject}")

class Doctor:
  def __init__(self, name, year_of_birth, specialist):
    self.name = name
    self.year_of_birth = year_of_birth
    self.specialist = specialist
  def describe(self):
    print(f"{self.name} - YoB: {self.year_of_birth} - Specialist: {self.specialist}")

class Ward:
  def __init__(self, name):
    self.name = name
    self.set_person = []

  def add_person(self, person):
    self.set_person.append(person)

  def count_doctor(self):
    count = 0
    for person in self.set_person:
     if isinstance(person, Doctor):
       count += 1
    return count

  def sort_Age(self):
    return  sorted(self.set_person, key = lambda person: person.year_of_birth, reverse = True)

  def compute_avarage_Yob_Teacher(self):
    sum = 0
    count = 0
    for person in self.set_person:
      if isinstance(person, Teacher):
        sum += person.year_of_birth
        count += 1
    return sum / count

  def describe(self):
    print("Ward name:", self.name)
    for person in self.set_person:
        person.describe()

In [68]:
student1 = Student ( name =" studentA ", year_of_birth= 2010 , grade ="7")
student1.describe ()


teacher1 = Teacher ( name =" teacherA ", year_of_birth=1969 , subject =" Math ")
teacher1.describe ()


doctor1 = Doctor ( name =" doctorA ", year_of_birth=1945 , specialist =" Endocrinologists ")
doctor1.describe ()

print ()
teacher2 = Teacher ( name =" teacherB ", year_of_birth=1995 , subject =" History ")
doctor2 = Doctor ( name =" doctorB ", year_of_birth=1975 , specialist =" Cardiologists ")
ward1 = Ward ( name =" Ward1 ")
ward1.add_person ( doctor1 )
ward1.add_person ( doctor2 )
ward1.add_person ( student1 )
ward1.add_person ( teacher1 )
ward1.add_person ( teacher2 )
ward1.describe()

print("Number of doctor: ", ward1.count_doctor())
for person in ward1.sort_Age():
  person.describe()

print("Average Yob of Teacher: ", ward1.compute_avarage_Yob_Teacher())


 studentA  - YoB: 2010 - Grade: 7
 teacherA  - YoB: 1969 - Subject:  Math 
 doctorA  - YoB: 1945 - Specialist:  Endocrinologists 

Ward name:  Ward1 
 doctorA  - YoB: 1945 - Specialist:  Endocrinologists 
 doctorB  - YoB: 1975 - Specialist:  Cardiologists 
 studentA  - YoB: 2010 - Grade: 7
 teacherA  - YoB: 1969 - Subject:  Math 
 teacherB  - YoB: 1995 - Subject:  History 
Number of doctor:  2
 studentA  - YoB: 2010 - Grade: 7
 teacherB  - YoB: 1995 - Subject:  History 
 doctorB  - YoB: 1975 - Specialist:  Cardiologists 
 teacherA  - YoB: 1969 - Subject:  Math 
 doctorA  - YoB: 1945 - Specialist:  Endocrinologists 
Average Yob of Teacher:  1982.0


In [70]:
#Q3
class Stack:
  def __init__(self, capacity):
    self.capacity = capacity
    self.stack = []

  def is_Empty(self):
    return len(self.stack) == 0

  def is_Full(self):
    return len(self.stack) == self.capacity

  def top(self):
    return self.stack[-1]

  def push(self, value):
    self.stack.append(value)


  def pop(self):
    popped_value = self.top()
    self.stack.remove(popped_value)
    return popped_value



In [71]:
stack1 = Stack(capacity = 5)
stack1.push(1)
stack1.push(2)

print(stack1.is_Full())

print(stack1.top())

print(stack1.pop())

print(stack1.top())

print(stack1.pop())

print(stack1.is_Empty())

False
2
2
1
1
True


In [72]:
#Q4
class Queue:
  def __init__(self, capacity):
    self.capacity = capacity
    self.queue = []
  def is_Empty(self):
    return len(self.queue) == 0

  def is_Full(self):
    return len(self.queue) == self.capacity

  def enqueue(self, value):
    self.queue.append(value)

  def front(self):
    return self.queue[0]

  def dequeue(self):
    front = self.front()
    self.queue.remove(front)
    return front





In [74]:
queue1 = Queue ( capacity =5)

queue1 . enqueue (1)
queue1 . enqueue (2)

print ( queue1 . is_Full () )

print ( queue1 . front () )

print ( queue1 . dequeue () )

print ( queue1 . front () )

print ( queue1 . dequeue () )

print ( queue1 . is_Empty () )


False
1
1
2
2
True


In [ ]:
# Multiple choice
#Q1


In [75]:
import torch
import torch . nn as nn
data = torch . Tensor ([1 , 2 , 3])
softmax_function = nn . Softmax ( dim =0)
output = softmax_function ( data )
assert round ( output [0]. item () , 2) == 0.09
output

tensor([0.0900, 0.2447, 0.6652])

In [76]:
#Q2
import torch
import torch.nn as nn
import math

data = torch . Tensor ([5 , 2, 4])
my_softmax = Softmax ()
output = my_softmax ( data )
assert round ( output [ -1]. item () , 2) == 0.26
output

tensor([0.7054, 0.0351, 0.2595])

In [80]:
#Q3
import torch
import torch.nn as nn
import math

data = torch . Tensor ([1 , 2, 300000000])
my_softmax = Softmax ()
output = my_softmax ( data )
assert round ( output [0]. item () , 2) == 0.0
output

tensor([0., 0., nan])

In [81]:
#Q4
import torch
import torch .nn as nn

class SoftmaxStable (nn. Module ):
  def __init__ ( self ):
    super (). __init__ ()

  def forward (self , x):
    x_max = torch .max(x, dim =0, keepdims = True )
    x_exp = torch .exp(x - x_max . values )
    partition = x_exp .sum (0, keepdims = True )
    return x_exp / partition


data = torch . Tensor ([1 , 2, 3])
softmax_stable = SoftmaxStable ()
output = softmax_stable ( data )
assert round ( output [ -1]. item () , 2) == 0.67
output

tensor([0.0900, 0.2447, 0.6652])

In [89]:
from abc import ABC, abstractclassmethod

class Person(ABC):
  def __init__(self, name, yob):
    self.name = name
    self.yob = yob

  def get_yob(self):
    return self.yob

  @abstractclassmethod
  def describe(self):
    pass


class student(Person):
  def __init__(self, name, yob, grade):
    super().__init__(name, yob)
    self.grade = grade

  def describe(self):
    print(f"Student - Name: {self.name} - YoB: {self.yob} - Grade: {self.grade}")

student1 = student ( name =" studentZ2023 ", yob =2011 , grade ="6")
assert student1.yob == 2011
student1 . describe ()

Student - Name:  studentZ2023  - YoB: 2011 - Grade: 6


In [92]:
#Q6
from abc import ABC, abstractclassmethod

class Person(ABC):
  def __init__(self, name, yob):
    self.name = name
    self.yob = yob

  def get_yob(self):
    return self.yob

  @abstractclassmethod
  def describe(self):
    pass


class teacher(Person):
  def __init__(self, name, yob, subject):
    super().__init__(name, yob)
    self.subject = subject

  def describe(self):
    print(f"Teacher - Name: {self.name} - YoB: {self.yob} - Subject: {self.subject}")

In [91]:
teacher1 = teacher ( name =" teacherZ2023 ", yob =1991 , subject =" History ")
assert teacher1 .yob == 1991
teacher1 . describe ()

Student - Name:  teacherZ2023  - YoB: 1991 - Subject:  History 


In [ ]:
# Q7 apply for person "Doctor", It is the same way with two implements above

In [100]:
# Q8
class Student:
  def __init__(self, name, year_of_birth, grade):
    self.name = name
    self.year_of_birth = year_of_birth
    self.grade = grade
  def describe(self):
    print(f"{self.name} - YoB: {self.year_of_birth} - Grade: {self.grade}")

class Teacher:
  def __init__(self, name, year_of_birth, subject):
    self.name = name
    self.year_of_birth = year_of_birth
    self.subject = subject
  def describe(self):
    print(f"{self.name} - YoB: {self.year_of_birth} - Subject: {self.subject}")

class Doctor:
  def __init__(self, name, year_of_birth, specialist):
    self.name = name
    self.year_of_birth = year_of_birth
    self.specialist = specialist
  def describe(self):
    print(f"{self.name} - YoB: {self.year_of_birth} - Specialist: {self.specialist}")

class Ward:
  def __init__(self, name):
    self.name = name
    self.set_person = []

  def add_person(self, person):
    self.set_person.append(person)

  def count_doctor(self):
    count = 0
    for person in self.set_person:
     if isinstance(person, Doctor):
       count += 1
    return count

  def sort_Age(self):
    return  sorted(self.set_person, key = lambda person: person.year_of_birth, reverse = True)

  def compute_avarage_Yob_Teacher(self):
    sum = 0
    count = 0
    for person in self.set_person:
      if isinstance(person, Teacher):
        sum += person.year_of_birth
        count += 1
    return sum / count

  def describe(self):
    print("Ward name:", self.name)
    for person in self.set_person:
        person.describe()

ward1 = Ward ( name =" Ward1 ")
student1 = Student ( name =" studentA ", year_of_birth =2010 , grade ="7")
teacher1 = Teacher ( name =" teacherA ", year_of_birth =1969 , subject =" Math ")
teacher2 = Teacher ( name =" teacherB ", year_of_birth =1995 , subject =" History ")
doctor1 = Doctor ( name =" doctorA ", year_of_birth =1945 , specialist =" Endocrinologists ")

print(ward1.count_doctor())


doctor2 = Doctor ( name =" doctorB ", year_of_birth =1975 , specialist =" Cardiologists ")
ward1 . add_person ( student1 )
ward1 . add_person ( teacher1 )
ward1 . add_person ( teacher2 )
ward1 . add_person ( doctor1 )
ward1 . add_person ( doctor2 )
ward1 . count_doctor ()

0


2

In [102]:
# Q9
stack2 = Stack(5)
stack2.push(1)
assert stack2.is_Full() == False
stack2.push(2)
print(stack2.is_Full())


False


In [103]:
# Q10
stack3 = Stack ( capacity =5)
stack3 . push (1)
assert stack3 . is_Full () == False
stack3 . push (2)
print ( stack3 . top ())

2


In [105]:
# Q11
queue2 = Queue ( capacity =5)
queue2 . enqueue (1)
assert queue1 . is_Full () == False
queue2 . enqueue (2)
print ( queue2 . is_Full ())

False


In [106]:
queue3 = Queue ( capacity =5)
queue3 . enqueue (1)
assert queue3 . is_Full () == False
queue3 . enqueue (2)
print ( queue3 . front ())

1
